### PR TITLE
feat(UltraPicker): add support for custom font and size

### PR DESCRIPTION
**Pull request by edwardjones-sportsbet**
Version 0.1.4 - Added support for custom Font and Size on items in the picker

### CODE REVIEW

**Comment by timsawtell-sportsbet** [comment]
It looks like react-native upgrades since this project started changed the rules about setting state in componentWillReceiveProps.

Could you please change that function implementation to be 
componentWillReceiveProps(nextProps) {
        this.setState(this._stateBasedOnProps(nextProps))
    }
in UltraPickerIOS.tsx and re-test that there is no warning generated (and functionality isn't impacted).

Thanks!

**Comment by edwardjones-sportsbet** [comment]
I have made the requested changes to componentWillReceiveProps

**Comment by timsawtell-sportsbet** [comment]
It looks like the user is only allowed to specify a new fontSize if they have also specified a new fontFamily. Would you be able to make it so that the user is able to set either of these independently, and fall back to default family/size if they don't provide one?

**Comment by edwardjones-sportsbet** [comment]
Ability to specify a `fontSize` and `fontFamlily` independently added. Otherwise it falls back to HelveticaNeue - Size 17

**Pull request merged**
